# Set up and run this Streamlit App
import streamlit as st
from helper_functions import llm # <--- This is the helper function that we have created 🆕
from logics import customer_query_handler as cqh
from helper_functions.utility import check_password  

# Check if the password is correct.  
if not check_password():  
     st.stop()

# region <--------- Streamlit App Configuration --------->
st.set_page_config(
    layout="centered",
    page_title="My Streamlit App"
)
# endregion <--------- Streamlit App Configuration --------->

st.title("Streamlit App")

form = st.form(key="form")
form.subheader("Prompt")

user_prompt = form.text_area("Enter your prompt here", height=200)

if form.form_submit_button("Submit"):
    st.toast(f"User Input Submitted - {user_prompt}")
    #response = llm.get_completion(user_prompt) # <--- This calls the helper function that we have created 🆕

    # calling customer_query_handler's function - Task 2 part 1 testing
    #response = customer_query_handler.identify_category_and_courses(user_prompt)
    #st.write(response) # <--- This displays the response generated by the LLM onto the frontend 🆕


    # Task 2 Part 3 testing
    #identified_course = cqh.identify_category_and_courses(user_prompt)
    # course_details = cqh.get_course_details(identified_course) 
    #response = cqh.generate_response_based_on_course_details(user_prompt,course_details)
    #st.write(response)


    # Task 3 testing
    response = cqh.process_user_message(user_prompt)
    st.write(response)

    print(f"User Input is \"{user_prompt}\"")
    print(f"Final reponse: \n{response}")


#=======================
# Testing the function to make sure it works for Task 2 part 2
# This part should not be included as part of the Python script.

# This is a sample input to test the function

# sample_input = [{'category': 'Programming and Development','course_name': 'Web Development Bootcamp'},
#                {'category': 'Data Science & AI', 'course_name': 'Data Science with Python'},
#                {'category': 'Data Science & AI', 'course_name': 'AI and Machine Learning for Beginners'}]


#product_details = cqh.get_course_details(sample_input)
#print(product_details)
